[package]
name = "git-latest-commit"
description = "Add data about the latest git commit for a project at build time, for run-time reporting."
version = "0.1.0"
authors = ["C J Silverio <ceejceej@gmail.com>"]

[dependencies]
quick-error = "1.1.0"
git2 = "0.5.0"
